from cassandra
#EXPOSE 7000 7199 9042 8888 8012 9160 22 61621
#RUN echo "deb http://www.apache.org/dist/cassandra/debian 311x main" | tee -a /etc/apt/sources.list.d/cassandra.sources.list
#RUN gpg --keyserver pgp.mit.edu --recv-keys F758CE318D77295D && gpg --export --armor F758CE318D77295D | apt-key add -
#RUN gpg --keyserver pgp.mit.edu --recv-keys 2B5C1B00 && gpg --export --armor 2B5C1B00 | apt-key add -
#RUN gpg --keyserver pgp.mit.edu --recv-keys 0353B12C && gpg --export --armor 0353B12C | apt-key add -
#RUN apt-get update
#RUN apt-get install -y --allow-unauthenticated cassandra
#CMD ["cassandra", "-Rf"]
