#Services config
cassandra:
  hostname: localhost
  port: 9042
  keyspace: happypatients
redis:
  hostname: localhost
  port: 6379
policyserver:
  hostname: localhost
  port: 8080
  path: /policyserver/webapi/myresource
  protocol: http